### ISSUE TITLE
Portfolio Value graph acts strangely

### ISSUE THREAD

**Issue by K0wang** [pViewCorp/bugs#6]
## Describe the bug

The portfolio value graph moves up and down once opened.
## To Reproduce

1. Run pView
2. Open file: [test.zip](https://github.com/pViewCorp/bugs/files/5655851/test.zip)
4. Click on Portfolio Value on the titled pane
5. Click on it again

## Environment
- Version: 0.6.1
- Runtime: 14.0.2+12 OpenJDK 64-Bit Server VM
- Operating System: Windows 10 amd64

**Comment by ProfessorShep** [comment]
The download you posted is corrupted. Your PVF file is empty: 
![image](https://user-images.githubusercontent.com/47160266/101359800-c5229980-386a-11eb-8880-022bc9de573c.png)

**Comment by K0wang** [comment]
Ok, try using a random pvf file to produce the bug.

**Comment by ProfessorShep** [comment]
@K0wang It's working for me. Can you try re-posting your file?

**Comment by K0wang** [comment]
Can not right now.

**Comment by ProfessorShep** [comment]
Alright do it later

**Comment by K0wang** [comment]
Ok

**Comment by ProfessorShep** [comment]
This will be fixed in 0.6.5

**Comment by ProfessorShep** [comment]
Version 0.6.5 has been released
